apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-clb-service
  labels:
    app: usermgmt-restapp
  annotations:
    # Classic Load Balancer Configuration
    service.beta.kubernetes.io/aws-load-balancer-type: "clb"
    
    # Load Balancer will be created in public subnets
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    
    # Health Check Configuration
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    
    # Connection Settings
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"

    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: usermgmt-restapp
  ports:
  - name: http
    port: 80
    targetPort: 8095
    protocol: TCP